name = "tradein-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
workers_dev = true
account_id = "cf4198e651bf3009877d49f688c9d88e"

[vars]
STORE_EMAIL = "contact@cambridgetcg.com"
ADMIN_SECRET = "tcg-admin-2026-cambridgetcg"

[[kv_namespaces]]
binding = "BUYLIST"
id = "de8e07b4a9df4551b24b3255c20e6907"

[[kv_namespaces]]
binding = "SUBMISSIONS"
id = "60ccd7b42b914421b0ed225a11ac4169"

[[routes]]
pattern = "tradein-api.cambridgetcg.com/*"
zone_name = "cambridgetcg.com"
