/**
 * API client for Buy List endpoint.
 * Uses sessionStorage for caching within a browser session.
 */
// v2: Use local buylist data (CardRush A- prices → GBP)
// Worker API at tradein-api.cambridgetcg.workers.dev (once deployed)
// Fallback: serve buylist.json from same origin
const API_BASE = '';
const CACHE_KEY = 'ctcg_buylist_v4';
const CACHE_TTL = 5 * 60 * 1000; // 5 minutes
const FETCH_TIMEOUT = 15000; // 15 seconds

function fetchWithTimeout(url, opts) {
  var controller = new AbortController();
  var id = setTimeout(function() { controller.abort(); }, FETCH_TIMEOUT);
  opts = opts || {};
  opts.signal = controller.signal;
  return fetch(url, opts).finally(function() { clearTimeout(id); });
}

const BuyListAPI = {
  /**
   * Fetch buy list (cached in sessionStorage for 5 min).
   * Returns { count, buying_count, buy_rate, items: [...] }
   */
  async getBuyList() {
    const cached = sessionStorage.getItem(CACHE_KEY);
    if (cached) {
      const parsed = JSON.parse(cached);
      if (Date.now() - parsed._ts < CACHE_TTL) {
        return parsed.data;
      }
    }

    // v2: fetch static buylist.json (generated by build-buylist.py)
    const resp = await fetchWithTimeout('/data/buylist.json');
    if (!resp.ok) throw new Error('Buy list fetch failed: ' + resp.status);
    const raw = await resp.json();
    // Transform v2 format to match expected UI format (snake_case)
    const data = {
      count: raw.stats.totalCards,
      buying_count: raw.stats.totalCards,
      fx_rate: raw.fxRate,
      generated_at: raw.generatedAt,
      pricing: raw.pricing,
      sets: raw.sets,
      items: raw.items.map(function(c) {
        return {
          sku: c.sku,
          card_number: c.cardNumber,
          set_code: c.setCode,
          set_name: c.setName,
          name: c.name,
          rarity: c.rarity,
          is_parallel: c.isParallel,
          cash_price: c.cashPrice,
          credit_price: c.creditPrice,
          mint_cash_price: c.mintCashPrice,
          mint_credit_price: c.mintCreditPrice,
          cash_want: 99, // always buying for trade-in
          credit_want: 99,
          image_url: c.imageUrl,
          image_fallback: c.imageFallback || '',
          cardrush_url: c.cardrushUrl,
          wholesale_price: c.wholesalePrice,
          stock: c.stock,
          price_source: c.priceSource,
        };
      }),
    };

    sessionStorage.setItem(CACHE_KEY, JSON.stringify({ _ts: Date.now(), data }));
    return data;
  },

  /**
   * Submit a trade-in request.
   * Returns { reference, quoted_cash_total, quoted_credit_total, ... }
   */
  async submitTradeIn(data) {
    const resp = await fetchWithTimeout(API_BASE + '/tradein', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    const result = await resp.json();
    if (!resp.ok) throw new Error(result.error || 'Submission failed');
    return result;
  },

  /**
   * Check trade-in status by reference + email.
   * Returns { reference, status, items, ... }
   */
  async getTradeInStatus(reference, email) {
    const resp = await fetchWithTimeout(
      API_BASE + '/tradein/' + encodeURIComponent(reference)
      + '?email=' + encodeURIComponent(email)
    );
    const result = await resp.json();
    if (!resp.ok) throw new Error(result.error || 'Status check failed');
    return result;
  },
};
